# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: min_url_development
  pool: 5
  timeout: 5000
  username: v4
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: min_url_test
  pool: 5
  timeout: 5000
  username: v4
  password:

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5
